# Generated by Django 2.2.28 on 2023-10-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban_group_spy', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DouList',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('alt', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'DouList',
            },
        ),
    ]
