# Generated by Django 2.2.28 on 2023-10-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('douban_group_spy', '0006_doulist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
