# Generated by Django 2.2.28 on 2023-10-11 11:15

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('douban_group_spy', '0007_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoulistPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=24, unique=True)),
                ('alt', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('photo_list', jsonfield.fields.JSONField(default=[])),
                ('is_matched', models.BooleanField(default=False)),
                ('keyword_list', jsonfield.fields.JSONField(default=[])),
                ('comments', jsonfield.fields.JSONField(default=[])),
                ('comment', models.CharField(blank=True, max_length=128, null=True)),
                ('is_collected', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'DoulistPost',
            },
        ),
    ]
