# Generated by Django 2.2.28 on 2023-10-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('douban_group_spy', '0008_doulistpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doulistpost',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='doulistpost',
            name='is_collected',
        ),
        migrations.RemoveField(
            model_name='doulistpost',
            name='is_matched',
        ),
        migrations.RemoveField(
            model_name='doulistpost',
            name='keyword_list',
        ),
    ]
